#!/bin/bash

if [ "$APPLICATION_NAME" == "crowdserve-dev" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    cd /mnt/frontend_app
    rm -rf ./.next
    rm -rf ./package.json
    rm -rf ./node_modules
    cp -rf ./dist/standalone/.next ./.next
    cp -rf ./dist/standalone/package.json ./package.json
    cp -rf ./dist/standalone/node_modules ./node_modules
    cp -rf ./dist/static ./.next/static
    rm -rf ./dist
fi

if [ "$APPLICATION_NAME" == "crowdserve-prod" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 423361175163.dkr.ecr.ap-southeast-1.amazonaws.com

    docker pull 423361175163.dkr.ecr.ap-southeast-1.amazonaws.com/crowdserve-frontend-app
fi
