#!/bin/bash

if [ "$APPLICATION_NAME" == "crowdserve-dev" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    pm2 start crowdserve-frontend-app
fi

if [ "$APPLICATION_NAME" == "crowdserve-prod" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    docker run -d --restart=always \
        --name=crowdserve-frontend-app \
        --network=crowdserve-prod \
        -p 8080:8080 \
        -e NODE_ENV="production" \
        -e PORT=8080 \
        423361175163.dkr.ecr.ap-southeast-1.amazonaws.com/crowdserve-frontend-app
fi