#!/bin/bash

if [[ "$APPLICATION_NAME" == "crowdserve-dev" || "$APPLICATION_NAME" == "crowdserve-stag" ]] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    pm2 stop crowdserve-frontend-app
fi

if [ "$APPLICATION_NAME" == "crowdserve-prod" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-app" ]; then
    docker rm -f crowdserve-frontend-app
fi
